language: php

matrix:
  include:
    - php: '5.3'
      dist: precise
      env:
        - APC=on
        - INST_APC=on
        - OPENSSL=on
    - php: '5.4'
      env:
        - INST_APC=on
        - APC=on
    - php: '5.5'
      env:
        - INST_APCU=on
        - APCU=on
    - php: '5.6'
      env:
        - APCU=on
    - php: '7.0'
      env:
        - APCU=on
    - php: '7.0'
      env:
        - APC=on
        - APCU=on
    - php: '7.1'
      env:
        - APCU=on
    - php: '7.2'
      env:
        - APCU=on
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $OPENSSL == "on" ]]; then pecl install -f openssl ; fi
  - if [[ $OPENSSL == "on" ]]; then echo "extension = openssl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $INST_APC == "on" ]]; then echo no | pecl install -f apc ; fi
  - if [[ $APC == "on" ]]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $INST_APCU == "on" ]]; then echo no | pecl install -f apcu ; fi
  - if [[ $APCU == "on" ]]; then echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: 
  - phpunit -c tests
