language: php

matrix:
  include:
    - php: '5.3'
      dist: precise
    - php: '5.4'
    - php: '5.5'
    - php: '5.6'
      env:
        - APCU=on
    - php: '7.0'
      env:
        - APCU=on
    - php: '7.1'
      env:
        - APCU=on
    - php: '7.2'
      env:
        - APCU=on

before_install:
  - if [[ $OPENSSL == "on" ]]; then pecl install -f openssl ; fi
  - if [[ $INST_APC == "on" ]]; then echo yes | pecl install -f apc ; fi
  - if [[ $APC == "on" ]]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $INST_APCU == "on" ]]; then echo yes | pecl install -f apcu ; fi
  - if [[ $APCU == "on" ]]; then echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: 
  - phpunit -c tests
