language: php

matrix:
  include:
    - php: '5.3'
      dist: precise
      env:
        - APC=on
        - OPENSSL=on
    - php: '5.4'
      env:
        - APC=on
    - php: '5.5'
      env:
        - APCU=on
    - php: '5.6'
      env:
        - APCU=on
    - php: '7.0'
      env:
        - APCU=on
    - php: '7.0'
      env:
        - APCU=on
    - php: '7.1'
      env:
        - APCU=on
    - php: '7.2'
      env:
        - APCU=on
  allow_failures:
    - php: hhvm

before_install:
  - echo $TRAVIS_PHP_VERSION
  - phpenv version-name
  - sh -c 'if [ $OPENSSL == 'on' ]; then pecl install -f openssl & echo "extension = openssl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - sh -c 'if [ $APC == 'on' ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - sh -c 'if [ $APCU == 'on' ]; then echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: 
  - phpunit -c tests
